/*********************************************************************
 *                                                                   *
 * MODULE NAME :  cnrez.h                AUTHOR:  Rick Fishman       *
 * DATE WRITTEN:  10-06-92                                           *
 *                                                                   *
 * DESCRIPTION:                                                      *
 *                                                                   *
 *  Common definitions and function prototypes for CNREZ.EXE         *
 *                                                                   *
 * HISTORY:                                                          *
 *                                                                   *
 *  10-06-92 - File Created                                          *
 *                                                                   *
 *  Rick Fishman                                                     *
 *  Code Blazers, Inc.                                               *
 *  4113 Apricot                                                     *
 *  Irvine, CA. 92720                                                *
 *  CIS ID: 72251,750                                                *
 *                                                                   *
 *********************************************************************/

#define CNR_SAMPLE       30
#define ID_RESOURCES     1
#define ICO_DOIT         20
#define IDM_ICON         100
#define IDM_NAME         110
#define IDM_TREE         120
#define IDM_DETAILS      130
#define IDM_TEXT         140
